INSERT INTO cinema.dbo.MovieHall (Hall_id, Type, Row_sum, Line_sum, Add_price) VALUES (1, '激光巨幕', 20, 10, 40);
INSERT INTO cinema.dbo.MovieHall (Hall_id, Type, Row_sum, Line_sum, Add_price) VALUES (2, '杜比', 20, 10, 15);
INSERT INTO cinema.dbo.MovieHall (Hall_id, Type, Row_sum, Line_sum, Add_price) VALUES (3, '3D 杜比', 20, 10, 30);
INSERT INTO cinema.dbo.MovieHall (Hall_id, Type, Row_sum, Line_sum, Add_price) VALUES (6, 'VIP', 10, 5, 100);
INSERT INTO cinema.dbo.MovieHall (Hall_id, Type, Row_sum, Line_sum, Add_price) VALUES (5, '激光', 20, 10, 3);
INSERT INTO cinema.dbo.MovieHall (Hall_id, Type, Row_sum, Line_sum, Add_price) VALUES (4, 'IMAX 激光巨幕', 30, 15, 40);
INSERT INTO cinema.dbo.MovieHall (Hall_id, Type, Row_sum, Line_sum, Add_price) VALUES (7, '激光', 20, 10, 3);
INSERT INTO cinema.dbo.MovieHall (Hall_id, Type, Row_sum, Line_sum, Add_price) VALUES (8, 'VIP', 10, 5, 100);
INSERT INTO cinema.dbo.MovieHall (Hall_id, Type, Row_sum, Line_sum, Add_price) VALUES (9, '巨幕 杜比', 20, 10, 40);
INSERT INTO cinema.dbo.MovieHall (Hall_id, Type, Row_sum, Line_sum, Add_price) VALUES (10, '激光', 20, 10, 3);